### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by davies-jack**
- Moving position of link to live app on README.md to top of the file
- Moving position of app logo to top of the README.md file
- Adding installation instructions to README.md
- Adding usage / screenshots to README.md
- Adding `readme-images` folder with three screenshots
- Fixing contact links so they are links instead of images

#1

### CODE REVIEW

**Comment by Gautam-Arora24** [comment]
It looks good @jackethdavies

**Comment by Gautam-Arora24** [comment]
Great work @jackethdavies

**Comment by davies-jack** [comment]
would you be able to add the `hacktoberfest-accepted` label to this pull request @Gautam-Arora24? so it counts towards my hacktoberfest pull requests? :)

**Comment by Gautam-Arora24** [comment]
Does it counts even after accepting the pull request? If Yes, I can surely do that

**Comment by davies-jack** [comment]
I'm not too sure, although I think so

**Comment by Gautam-Arora24** [comment]
Lemme check

**Comment by davies-jack** [comment]
Did you check by any chance? @Gautam-Arora24

**Comment by Gautam-Arora24** [comment]
I have added hacktoberfest-accepted label in this pull request

**Comment by davies-jack** [comment]
@Gautam-Arora24  - Thank you very much, just a note: you spelt hacktober wrong in `hacktoberfes-accepted`

Have a great day :D

**Comment by Gautam-Arora24** [comment]
Did it count towards Hacktoberfest?

**Comment by davies-jack** [comment]
It is in a review period so I think it worked! Thanks very much @Gautam-Arora24

**Comment by Gautam-Arora24** [comment]
Your Welcome :)

**Pull request merged**
